
CREATE TABLE tb_productos
(
	NU_ID_PRODUCTO INT IDENTITY(1,1)  PRIMARY KEY,
	TXT_NOMBRE_PRODUCTO NVARCHAR(250),
	TXT_PRODUCTO_CONTENIDO NVARCHAR(250),
	NU_PRODUCTO_CONTENIDO INT,
	TXT_FECHA_PRODUCTO NVARCHAR(15),
	TXT_PRODUCTO_CODIGO NVARCHAR(50) UNIQUE,
    NUM_CANTIDAD_BUSQUEDA INT DEFAULT 0,
    TX_SITREG CHAR(1) DEFAULT '1',
    TX_USUREG VARCHAR(100) NULL,
    FE_FECHA_REG DATE DEFAULT GETDATE(),
    TX_USUACT VARCHAR(100)  NULL,
    FE_FECHA_ACT DATETIME NULL,
    TX_USUELI VARCHAR(100) NULL,
    FE_FECHA_ELI DATETIME NULL
)
GO

CREATE TABLE tb_producto_detalle
(
	NU_ID_PRODUCTO_DETALLE INT IDENTITY(1,1) PRIMARY KEY,
    NU_ID_PRODUCTO INT,
    TX_DESCRIPCION VARCHAR(100) NOT NULL,
	TX_SITREG CHAR(1) DEFAULT '1',
    TX_USUREG VARCHAR(100) NULL,
    FE_FECHA_REG DATE  DEFAULT GETDATE(),
    TX_USUACT VARCHAR(100)  NULL,
    FE_FECHA_ACT DATETIME  NULL,
    TX_USUELI VARCHAR(100) NULL,
    FE_FECHA_ELI DATETIME  NULL,
    CONSTRAINT FK_PRODUCTODETALLE_PRODUCTO
	FOREIGN KEY (NU_ID_PRODUCTO) REFERENCES tb_productos(NU_ID_PRODUCTO)
)
GO